name = "lean-crypto-hash"
version = "0.1.0"
defaultTargets = ["Crypto", "test", "md5sum", "sha1sum", "sha224sum", "sha256sum", "sha384sum", "sha1sum", "sha512sum"]
testRunner = "test"

[[lean_lib]]
name = "Crypto"

# Test executable
[[lean_exe]]
name = "test"
root = "Test"

# Hash CLI tools
[[lean_exe]]
name = "md5sum"
root = "md5sum"

[[lean_exe]]
name = "sha1sum"
root = "sha1sum"

[[lean_exe]]
name = "sha224sum"
root = "sha224sum"

[[lean_exe]]
name = "sha256sum"
root = "sha256sum"

[[lean_exe]]
name = "sha384sum"
root = "sha384sum"

[[lean_exe]]
name = "sha512sum"
root = "sha512sum"



